[package]
name = "heraclitus"
version = "0.1.0"
authors = ["xuorig <mgiroux0@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
clap = "2.3"
serde = { version = "1.0", features = ["derive"] }
